version: "2"
services:
    agent:
        image: zabbix/zabbix-agent:alpine-3.2-latest
        privileged: true
        environment: 
            - ZBX_HOSTNAME=zabbix-monitoring
            - ZBX_SERVER_HOST=65.21.13.253
            - ZBX_SERVER_PORT=1336
        ports:
            - "1343:10050"
